import History from './components/History/History'

import './App.css'

const initialHistoryList = [
  {
    orderId: 1,
    customer: 'Karita Klimochkin',
    country: 'Sweden',
    address: '8978 Westridge Park',
    productTitle: 'Yellow-bellied marmot',
    productDescription: 'Bread - Flat Bread',
    date: '21/08/2020',
    status: 'Delivered',
  },
  {
    orderId: 2,
    customer: 'Ferne Roman',
    country: 'China',
    address: '1370 Ridge Oak Pass',
    productTitle: 'Two-toed sloth',
    productDescription: 'Asparagus - White, Fresh',
    date: '24/07/2020',
    status: 'Completed',
  },
  {
    orderId: 3,
    customer: 'Ranee Millins',
    country: 'Cuba',
    address: '403 Lukken Plaza',
    productTitle: 'Grenadier, purple',
    productDescription: 'Anchovy Fillets',
    date: '21/09/2019',
    status: 'Prepared',
  },
  {
    orderId: 4,
    customer: 'Jo ann Sowood',
    country: 'Sweden',
    address: '2401 Ludington Park',
    productTitle: 'Bandicoot, southern brown',
    productDescription: 'Wine - Chardonnay Mondavi',
    date: '28/07/2021',
    status: 'Delivered',
  },
  {
    orderId: 5,
    customer: 'Shelia Gumb',
    country: 'China',
    address: '51 Calypso Hill',
    productTitle: 'Western palm tanager (unidentified)',
    productDescription: 'Squash - Pepper',
    date: '28/09/2019',
    status: 'Completed',
  },
  {
    orderId: 6,
    customer: 'Montgomery Cron',
    country: 'Kazakhstan',
    address: '8675 Autumn Leaf Street',
    productTitle: 'Three-banded plover',
    productDescription: 'Nantuket Peach Orange',
    date: '04/11/2021',
    status: 'Delivered',
  },
  {
    orderId: 7,
    customer: 'Judas Rozet',
    country: 'Indonesia',
    address: '03 Barby Terrace',
    productTitle: 'Monitor, white-throated',
    productDescription: 'Island Oasis - Mango Daiquiri',
    date: '15/06/2021',
    status: 'Prepared',
  },
  {
    orderId: 8,
    customer: 'Sherman Stienham',
    country: 'Colombia',
    address: '61424 Arapahoe Parkway',
    productTitle: 'Waxbill, blue',
    productDescription: 'Mushroom - Morels, Dry',
    date: '13/09/2020',
    status: 'Delivered',
  },
  {
    orderId: 9,
    customer: 'Anton Tierny',
    country: 'Indonesia',
    address: '5 Northwestern Parkway',
    productTitle: 'Tortoise, radiated',
    productDescription: 'Lid - Translucent, 3.5 And 6 Oz',
    date: '08/05/2021',
    status: 'Delivered',
  },
  {
    orderId: 10,
    customer: 'Ulysses Burdis',
    country: 'China',
    address: '0 Ludington Park',
    productTitle: 'Wallaby, agile',
    productDescription: 'Table Cloth 54x72 White',
    date: '21/06/2020',
    status: 'Completed',
  },
  {
    orderId: 11,
    customer: 'Rex Bramsom',
    country: 'Philippines',
    address: '41709 Evergreen Street',
    productTitle: 'Pig-tailed macaque',
    productDescription: 'Swiss Chard',
    date: '27/11/2021',
    status: 'Delivered',
  },
  {
    orderId: 12,
    customer: 'Maurine Olijve',
    country: 'Russia',
    address: '2453 Longview Street',
    productTitle: 'Tawny eagle',
    productDescription: 'Salami - Genova',
    date: '17/10/2021',
    status: 'Delivered',
  },
  {
    orderId: 13,
    customer: 'Shelley Gillan',
    country: 'Malaysia',
    address: '80799 Myrtle Pass',
    productTitle: 'Ground monitor (unidentified)',
    productDescription: 'Spice - Greek 1 Step',
    date: '02/12/2020',
    status: 'Delivered',
  },
  {
    orderId: 14,
    customer: 'Darnell Kernock',
    country: 'Aland Islands',
    address: '368 Porter Center',
    productTitle: 'Coot, red-knobbed',
    product_description: 'Napkin - Cocktail,beige 2 - Ply',
    date: '12/04/2021',
    status: 'Delivered',
  },
  {
    orderId: 15,
    customer: 'Avis Rewcassell',
    country: 'Russia',
    address: '5 Sheridan Place',
    productTitle: 'Mountain duck',
    product_description: 'Salt - Celery',
    date: '26/10/2019',
    status: 'Delivered',
  },
  {
    orderId: 16,
    customer: 'Dallas Saines',
    country: 'Ukraine',
    address: '94 Pankratz Drive',
    productTitle: 'White-headed vulture',
    productDescription: 'Basil - Pesto Sauce',
    date: '06/06/2020',
    status: 'Delivered',
  },
  {
    orderId: 17,
    customer: 'Marina Kolyagin',
    country: 'Afghanistan',
    address: '0861 Reindahl Point',
    productTitle: 'Phascogale, brush-tailed',
    productDescription: 'Hummus - Spread',
    date: '08/03/2021',
    status: 'Prepone',
  },
  {
    orderId: 18,
    customer: 'Malvin Gaskal',
    country: 'Canada',
    address: '19566 Di Loreto Lane',
    productTitle: 'Wallaby, red-necked',
    productDescription: 'Cheese - Bakers Cream Cheese',
    date: '19/12/2020',
    status: 'Completed',
  },
  {
    orderId: 19,
    customer: 'Nikki Goney',
    country: 'Vietnam',
    address: '997 Declaration Crossing',
    productTitle: 'Mara',
    productDescription: 'Rosemary - Dry',
    date: '22/03/2021',
    status: 'Delivered',
  },
  {
    orderId: 20,
    customer: 'Boote Barchrameev',
    country: 'China',
    address: '5411 Harbort Center',
    productTitle: 'Lechwe, kafue flats',
    productDescription: 'Coconut - Shredded, Unsweet',
    date: '02/03/2020',
    status: 'Completed',
  },
]

const App = () => <History initialHistoryList={initialHistoryList} />

export default App
